version: '2'
services:
  # client:
    # build: ../ureed-client/
    # ports:
      # - 4200:4200
    # volumes:
      # - ../ureed-client/src/:/app/src/
    # depends_on:
      # - server
    # env_file: .env

  server:
    build: ../ureed-server/
    ports:
      - 8000:8000
    links:
      - elasticsearch
      - database
    environment:
      - HOST:database
      - PORT:5432
      - DEBUG=true
    volumes:
      - ../ureed-server/:/usr/src/app/
    links:
      - redis
      - elasticsearch
    depends_on:
      - redis
      # - elasticsearch # Causes server not to start

  redis:
    image: redis:2.8

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.3
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ureed
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/postgres:/var/lib/postgresql/data
